# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 05:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='注册邮箱')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='昵称')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='姓名')),
                ('school', models.CharField(max_length=255, null=True, verbose_name='目前的学校')),
                ('sex', models.BooleanField(choices=[(False, '男'), (True, '女')], default=False, verbose_name='性别')),
                ('birthday', models.DateField(null=True, verbose_name='生日')),
                ('score', models.IntegerField(default=0, verbose_name='积分')),
                ('avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('is_staff', models.BooleanField(default=False, verbose_name='管理员')),
                ('is_active', models.BooleanField(default=True, verbose_name='当前状态')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('subscribed', models.BooleanField(default=True, verbose_name='订阅')),
                ('verification_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='验证码')),
                ('expire', models.DateTimeField(blank=True, null=True, verbose_name='验证码失效时间')),
                ('is_activated', models.BooleanField(default=False, verbose_name='是否激活')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Oauth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='名称')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='邮箱')),
                ('avatar_url', models.CharField(blank=True, max_length=255, verbose_name='头像url')),
                ('expire', models.DateTimeField(blank=True, null=True, verbose_name='token失效时间')),
                ('access_token', models.CharField(max_length=255, verbose_name='access_token')),
                ('refresh_token', models.CharField(blank=True, max_length=255, verbose_name='refresh_token')),
                ('provider', models.CharField(max_length=255, verbose_name='类别')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
